GET http://127.0.0.1:5555/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT21hciIsImlhdCI6MTY2NzU0NzkzMn0.SXUCAzGUrfjlbrzhfkbhKm40K5FWeAo-MPBM_Z0lNVY

###

POST http://127.0.0.1:5555/login
Content-Type: application/json

{
    "username": "Omar"
}